### ISSUE TITLE
Thank you for choosing After Dark

### ISSUE THREAD

**Issue by ghost** [tygerbytes/hugo-theme-after-dark#1]
The latest code may be found on my public git server: https://git.habd.as/comfusion/after-dark. I would make a mirror on GH but last I checked it was a paid feature only. The latest version includes several add-on modules and [help documentation](https://after-dark.habd.as).

**Comment by tygerbytes** [comment]
Thanks for your work on After Dark! It's a superb theme. 🥇 And thanks for the heads up. I'll check it out sometime.

I had a CI pipeline break when the original After Dark repo vanished from GitHub. It was a good lesson for me. 😄I'd love to fork a proper mirror if you were able to push one from Gitea to GitHub. Maybe something will come of go-gitea/gitea#3480

**Comment by ghost** [comment]
Sorry for any troubles you had. If you're looking to do pull mirrors they're pretty simple to get going on your own Gitea instance. I created the following Compose file which is what I base my git website off of: https://git.habd.as/comfusion/high-tea. Give it a try sometime if you want to create pull mirrors effortlessly. Fair warning though, you'll really start to notice the sluggishness of GitHub if you do.
